Link a design principle.
w3ctag/the-web-is-not-versioned pull request #4
Opened 2024-01-23 18:10 UTC by jyasskin

2024-01-25 00:49 UTC, tantek requested changes
As much as I dislike Markdown, since the document already uses Markdown links for such links, it's probably better to keep code stylistic consistency accordingly, e.g. from further down in the document:

`[one web](https://www.w3.org/TR/ethical-web-principles/#oneweb)`

Other than that, this seems useful to link explicitly.

2024-01-25 00:53 UTC, jyasskin commented
I did that first, but then I realized that Markdown links don't trigger Respec's support for references. It seems better to generate the https://pr-preview.s3.amazonaws.com/jyasskin/the-web-is-not-versioned/pull/4.html#references, and maybe the other links should get updated to also be real references.

2024-01-25 01:45 UTC, tantek approved these changes
That's interesting about Respect generating references in one case but not the other. Agreed. Looks good.

Would prefer to see an update of the other links deserving of explicit listing in references at the same time as this PR, but feel free to file a separate PR for that.

2024-12-03 16:01 UTC, rhiaro approved these changes

2024-12-03 16:03 UTC, merged